### ISSUE TITLE
Is there a way to use ":vital => true" with retrieve?

### ISSUE THREAD

**Issue by gonace** [crowdfavorite/gem-steps#11]
Is there a way to force the user to enter something with "retrieve" and ":vital => true"? I'm asking the user for a username/password that can't be blank.

:vital seems not to be supported for retrieve but is this something that could be added so it could be manage by steps instead of the user if so wanted?

Regards
Erik

**Comment by jondavidjohn** [comment]
Seems like this could easily be achieved by checking for empty-ness right?

``` ruby
  username = retrieve "Please enter your username: "
  error_and_exit if username.empty?
```
